-- AlterEnum: libera geração grátis para todos os modelos existentes.
-- Cada ADD VALUE precisa ser um statement próprio no Postgres.
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'SEM_CENSURA';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'DEEPDEEP';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'GPT_IMAGE_2';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'SEEDREAM_LITE';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'THEAIMODELAB_QUALITY';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'VEO_FAST';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'VEO_MAX';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'GROK_IMAGINE';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'GEMINI_OMNI';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'SEEDANCE_2';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'KLING_V3_TURBO';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'COMFYDEPLOY_WAN';
ALTER TYPE "FreeGenerationType" ADD VALUE IF NOT EXISTS 'MOTION_CONTROL';
